### ISSUE TITLE
[ios 10] compatibility with cistem aporio 

### ISSUE THREAD

**Issue by opendata26** [Matchstic/Xen#41]
When using cistem aporio opening and closing the toggles page adds a layer of blur (more blur each time until you can't see anything) which needs a respring to fix.

**Comment by Matchstic** [comment]
Definitely is a tweak compatibility issue! Surprised it's occurring, but it's occurring nonetheless. May have to talk to it's developer to sort this out.

**Comment by Matchstic** [comment]
Issues resolved for next update

**Comment by opendata26** [comment]
thanks
