### ISSUE TITLE
[iOs 10] Calendar doesn't show any event

### ISSUE THREAD

**Issue by diavolodeejay** [Matchstic/Xen#52]
So my calendar page doesn't show any event, even if I have some.
Look: [no events](http://i.imgur.com/sYqMpam.jpg), but [I have some events](http://i.imgur.com/n8ehSb7.jpg). They aren't in the default calendar if that can help.

**Comment by diavolodeejay** [comment]
I tried to add an event in the default calendar and it didn't show up

**Comment by Matchstic** [comment]
This is an issue with InfoStats 2 on iOS 10 - XenLS just queries it for data. I'll move this and the Weather issue across to the issues for IS2, as that's also the same cause.
