### ISSUE TITLE
[iOs 10] Weather page doesn't show anything

### ISSUE THREAD

**Issue by diavolodeejay** [Matchstic/Xen#53]
After adding the weather page it shows me no forecast...
[Look](http://i.imgur.com/BCwjNn8.png).
I'll update after the weather refresh period passed to see if it updates the page

**Comment by Matchstic** [comment]
This is an issue with InfoStats 2 on iOS 10 - XenLS just queries it for data. As per the Calendar issue, I'll move this one across too.

See: Matchstic/InfoStats2#9
