### ISSUE TITLE
Sometimes apps will freeze when launched from Launchpad

### ISSUE THREAD

**Issue by Matchstic** [Matchstic/Xen#6]
For some unknown reason, apps will freeze up when being launched from Launchpad or the Toggles page. This then needs a hard reset to exit from.

**Comment by omarthen3rd** [comment]
I can add to this. For me, the Camera app freezes for a solid 5 - 7 seconds before responding, I can send bug reports and what not if needed.

**Comment by Matchstic** [comment]
That would be great thanks; is this from the Launchpad page or the Toggles page?

**Comment by omarthen3rd** [comment]
Happens on the Toggles page, haven't seen it happen on the Launchpad page

**Comment by Matchstic** [comment]
Alright, does the device respond to any button presses in the meantime?

**Comment by Matchstic** [comment]
To add to this issue, I'm also experiencing a freeze of the device upon first unlock after applying the 9.3.3 jailbreak from boot. This appears to be caused by Xen HTML according to a crash log from 25/12; those seeing this freezing issue, do you also have Xen HTML installed and active on the lockscreen?

**Comment by Matchstic** [comment]
To add to this, I have been running a new build of Xen HTML that uses a different method to unload webpages after unlock. Since moving to this build, I no longer have experienced a freeze on unlocking or app launch. Thus, I will move this issue to the Xen HTML issue tracker, and will note it is fixed in the next build for that.
